## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
from sklearn.model_selection import train_test_split, KFold

In [3]:
X_train, X_test, y_train, y_test  = train_test_split(X,y)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
#各自切分
y0_index = range(40)
y1_index = range(40,200)
X0_train,x0_test,y0_train,y0_test = train_test_split(X[y0_index],y[y0_index],test_size = 10)
X1_train,x1_test,y1_train,y1_test = train_test_split(X[y1_index],y[y1_index],test_size = 10)

In [5]:
X_test=np.concatenate([x1_test, x0_test])
X_train = np.concatenate([X1_train, X0_train])
y_train=np.concatenate([y1_train, y0_train])
y_test=np.concatenate([y1_test, y0_test])

In [6]:
X_test

array([[705, 706, 707, 708, 709],
       [800, 801, 802, 803, 804],
       [345, 346, 347, 348, 349],
       [985, 986, 987, 988, 989],
       [430, 431, 432, 433, 434],
       [600, 601, 602, 603, 604],
       [500, 501, 502, 503, 504],
       [655, 656, 657, 658, 659],
       [685, 686, 687, 688, 689],
       [830, 831, 832, 833, 834],
       [140, 141, 142, 143, 144],
       [ 35,  36,  37,  38,  39],
       [155, 156, 157, 158, 159],
       [ 25,  26,  27,  28,  29],
       [105, 106, 107, 108, 109],
       [  0,   1,   2,   3,   4],
       [ 45,  46,  47,  48,  49],
       [ 55,  56,  57,  58,  59],
       [ 95,  96,  97,  98,  99],
       [ 70,  71,  72,  73,  74]])

In [7]:
#均衡的資料訓練集
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])